import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";

import "../App.css";

const API_BASE_URL = "http://127.0.0.1:8000";

const FarmerNotifications = () => {
  const location = useLocation();
  const navigate = useNavigate();

  const [farmerFile, setFarmerFile] = useState(
    location.state?.farmerFile || null
  );

  // Resource Estimation result is passed directly to this page.
  // Notifications should reuse these calculated values instead
  // of running Resource Estimation again.
  const resourceResult =
    location.state?.resourceResult || null;

  const [notifications, setNotifications] = useState([]);
  const [summary, setSummary] = useState(null);

  const [loading, setLoading] = useState(false);
  const [sendingSurvey, setSendingSurvey] = useState(null);
  const [sendingAll, setSendingAll] = useState(false);
  const [error, setError] = useState("");

  const handleFileChange = (event) => {
    const file = event.target.files?.[0];

    if (!file) {
      return;
    }

    setFarmerFile(file);
    setNotifications([]);
    setSummary(null);
    setError("");
  };

  const handleGenerateNotifications = async () => {
    setError("");

    // The notification page must receive the already generated
    // Resource Estimation result.
    if (!resourceResult?.success) {
      setError(
        "Please generate the Resource Estimation first, then open Farmer Notifications."
      );
      return;
    }

    if (!farmerFile) {
      setError(
        "The original farmer data file is required for mobile-number mapping."
      );
      return;
    }

    setLoading(true);
    setNotifications([]);
    setSummary(null);

    try {
      const formData = new FormData();

      // Original farmer file is used ONLY to map:
      // Survey Number -> Mobile Number.
      formData.append(
        "farmer_file",
        farmerFile
      );

      // Resource values come directly from the result
      // already generated by Resource Estimation.
      formData.append(
        "resource_result",
        JSON.stringify(resourceResult)
      );

      const response = await fetch(
        `${API_BASE_URL}/farmer-notifications`,
        {
          method: "POST",
          body: formData,
        }
      );

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(
          data.message ||
            "Failed to prepare farmer notifications."
        );
      }

      setNotifications(
        data.notifications || []
      );

      setSummary(
        data.summary || null
      );

    } catch (err) {
      console.error(
        "Farmer notification error:",
        err
      );

      setError(
        err.message ||
          "Unable to prepare farmer notifications."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleSendSms = async (notification) => {
    setError("");

    if (sendingAll) {
      setError("Please wait until Send All is completed.");
      return;
    }

    if (!notification?.eligible) {
      setError(
        "This farmer does not have a valid mobile number."
      );
      return;
    }

    if (!notification?.message) {
      setError(
        "SMS message is not available for this farmer."
      );
      return;
    }

    setSendingSurvey(
      notification.survey_number
    );

    try {
      const response = await fetch(
        `${API_BASE_URL}/farmer-notifications/send-sms`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            survey_number:
              notification.survey_number,
            farmer_name:
              notification.farmer_name,
            mobile_number:
              notification.mobile_number,
            message:
              notification.message,
          }),
        }
      );

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(
          data.message ||
            data.error ||
            "Failed to send SMS."
        );
      }

      setNotifications((current) =>
        current.map((item) =>
          item.survey_number ===
          notification.survey_number
            ? {
                ...item,
                sms_sent: Boolean(data.sent),
                sms_mode: data.mode || null,
                sms_status: data.sent
                  ? "Sent"
                  : "Preview",
              }
            : item
        )
      );

    } catch (err) {
      console.error(
        "SMS sending error:",
        err
      );

      setError(
        err.message ||
          "Unable to send SMS."
      );
    } finally {
      setSendingSurvey(null);
    }
  };

  const handleSendAll = async () => {
    setError("");

    const eligibleNotifications = notifications.filter(
      (notification) =>
        notification?.eligible &&
        notification?.message &&
        notification?.mobile_number
    );

    if (eligibleNotifications.length === 0) {
      setError("No eligible farmers are available for SMS.");
      return;
    }

    setSendingAll(true);

    let sentCount = 0;
    let failedCount = 0;

    try {
      for (const notification of eligibleNotifications) {
        try {
          const response = await fetch(
            `${API_BASE_URL}/farmer-notifications/send-sms`,
            {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                survey_number: notification.survey_number,
                farmer_name: notification.farmer_name,
                mobile_number: notification.mobile_number,
                message: notification.message,
              }),
            }
          );

          const data = await response.json();

          if (!response.ok || !data.success) {
            throw new Error(
              data.message ||
                data.error ||
                "Failed to send SMS."
            );
          }

          sentCount += 1;

          setNotifications((current) =>
            current.map((item) =>
              item.survey_number === notification.survey_number
                ? {
                    ...item,
                    sms_sent: Boolean(data.sent),
                    sms_mode: data.mode || null,
                    sms_status: data.sent ? "Sent" : "Preview",
                  }
                : item
            )
          );
        } catch (err) {
          failedCount += 1;

          setNotifications((current) =>
            current.map((item) =>
              item.survey_number === notification.survey_number
                ? {
                    ...item,
                    sms_status: "Failed",
                  }
                : item
            )
          );

          console.error(
            `SMS sending failed for ${notification.survey_number}:`,
            err
          );
        }
      }

      if (failedCount === 0) {
        setError(
          `All ${sentCount} eligible SMS notifications were sent successfully.`
        );
      } else {
        setError(
          `Send All completed: ${sentCount} sent, ${failedCount} failed.`
        );
      }
    } finally {
      setSendingAll(false);
    }
  };

  const formatCurrency = (value) => {
    const number = Number(value || 0);

    return `₹${number.toLocaleString(
      "en-IN",
      {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      }
    )}`;
  };

  return (
    <div className="module-page farmer-notifications-page">

      {/* HEADER */}
      <div className="module-header">

        <button
          type="button"
          className="back-button"
          onClick={() => navigate("/home")}
        >
          ← Back to Home
        </button>

        <h1>
          Farmer Notifications
        </h1>

        <p>
          Review individual farmer cost and
          treatment information before sending
          notifications.
        </p>

      </div>

      {/* RESOURCE ESTIMATION INPUT */}
      <div className="notification-upload-card">

        <h2>
          Resource Estimation Result
        </h2>

        <p>
          Farmer Notifications uses the Resource Estimation
          result already generated for this village.
          No second estimation is performed.
        </p>

        {resourceResult?.success ? (
          <>
            <p className="selected-file">
              Resource estimation:
              {" "}
              <strong>
                Completed
              </strong>
            </p>

            {farmerFile && (
              <p className="selected-file">
                Farmer data:
                {" "}
                <strong>
                  {farmerFile.name}
                </strong>
              </p>
            )}

            <button
              type="button"
              className="primary-button"
              onClick={handleGenerateNotifications}
              disabled={loading}
            >
              {loading
                ? "Preparing Notifications..."
                : "Load Farmer Notifications"}
            </button>
          </>
        ) : (
          <p className="notification-warning">
            No Resource Estimation result was passed to this page.
            Go back to Resource Estimation, generate the estimate,
            and then open Farmer Notifications from there.
          </p>
        )}

      </div>

      {/* ERROR */}
      {error && (
        <div className="notification-error">
          {error}
        </div>
      )}

      {/* SUMMARY */}
      {summary && (
        <div className="notification-summary">

          <div className="summary-box">
            <span>Total Farmers</span>
            <strong>
              {summary.total_records || 0}
            </strong>
          </div>

          <div className="summary-box">
            <span>Ready to Notify</span>
            <strong>
              {summary.eligible_notifications || 0}
            </strong>
          </div>

          <div className="summary-box">
            <span>Needs Review</span>
            <strong>
              {summary.ineligible_notifications || 0}
            </strong>
          </div>

        </div>
      )}

      {/* FARMER CARDS */}
      {notifications.length > 0 && (
        <div className="notifications-section">

          <div className="notifications-header">
            <h2>
              Individual Farmer Notifications
            </h2>

            <button
              type="button"
              className="notification-send-all-button"
              onClick={handleSendAll}
              disabled={sendingAll || notifications.every(
                (notification) => !notification.eligible
              )}
            >
              {sendingAll ? "Sending All..." : "🔔 Send All"}
            </button>
          </div>

          <div className="notification-grid">

            {notifications.map(
              (notification, index) => {

                const field =
                  notification.field || {};

                return (
                  <div
                    className="farmer-notification-card"
                    key={
                      notification.survey_number ||
                      index
                    }
                  >

                    {/* CARD HEADER */}
                    <div className="farmer-card-header">

                      <div>
                        <h3>
                          {notification.farmer_name ||
                            "Unknown Farmer"}
                        </h3>

                        <span>
                          Survey Number:{" "}
                          {notification.survey_number ||
                            "—"}
                        </span>
                      </div>

                      <span
                        className={
                          notification.eligible
                            ? "notification-status eligible"
                            : "notification-status review"
                        }
                      >
                        {notification.eligible
                          ? "Ready"
                          : "Review"}
                      </span>

                    </div>

                    {/* FARMER DETAILS */}
                    <div className="farmer-details">

                      <div>
                        <span>
                          Mobile Number
                        </span>

                        <strong>
                          {notification.mobile_number ||
                            "Not available"}
                        </strong>
                      </div>

                      <div>
                        <span>
                          Land Area
                        </span>

                        <strong>
                          {Number(
                            field[
                              "Land Area (Acres)"
                            ] || 0
                          ).toFixed(2)}{" "}
                          acres
                        </strong>
                      </div>

                      <div>
                        <span>
                          Crop
                        </span>

                        <strong>
                          {field.Crop || "—"}
                        </strong>
                      </div>

                      <div>
                        <span>
                          Disease
                        </span>

                        <strong>
                          {field.Disease || "—"}
                        </strong>
                      </div>

                      <div>
                        <span>
                          Severity
                        </span>

                        <strong>
                          {field[
                            "Disease Severity"
                          ] || "—"}
                        </strong>
                      </div>

                    </div>

                    {/* RESOURCE REQUIREMENT */}
                    <div className="notification-section">

                      <h4>
                        Resource Requirement
                      </h4>

                      <div className="resource-grid">

                        <div>
                          <span>
                            Fertilizer
                          </span>
                          <strong>
                            {Number(
                              field[
                                "Fertilizer Required (kg)"
                              ] || 0
                            ).toFixed(2)}{" "}
                            kg
                          </strong>
                        </div>

                        <div>
                          <span>
                            Pesticide
                          </span>
                          <strong>
                            {Number(
                              field[
                                "Pesticide Required (L)"
                              ] || 0
                            ).toFixed(2)}{" "}
                            L
                          </strong>
                        </div>

                        <div>
                          <span>
                            Spray Solution
                          </span>
                          <strong>
                            {Number(
                              field[
                                "Spray Solution Required (L)"
                              ] || 0
                            ).toFixed(2)}{" "}
                            L
                          </strong>
                        </div>

                        <div>
                          <span>
                            Drone Refills
                          </span>
                          <strong>
                            {field[
                              "Drone Refills"
                            ] || 0}
                          </strong>
                        </div>

                      </div>

                    </div>

                    {/* COST BREAKDOWN */}
                    <div className="notification-section">

                      <h4>
                        Cost Breakdown
                      </h4>

                      <div className="cost-list">

                        <div>
                          <span>
                            Fertilizer
                          </span>
                          <strong>
                            {formatCurrency(
                              field[
                                "Fertilizer Cost (INR)"
                              ]
                            )}
                          </strong>
                        </div>

                        <div>
                          <span>
                            Pesticide
                          </span>
                          <strong>
                            {formatCurrency(
                              field[
                                "Pesticide Cost (INR)"
                              ]
                            )}
                          </strong>
                        </div>

                        <div>
                          <span>
                            Water
                          </span>
                          <strong>
                            {formatCurrency(
                              field[
                                "Water Cost (INR)"
                              ]
                            )}
                          </strong>
                        </div>

                        <div>
                          <span>
                            Drone Operation
                          </span>
                          <strong>
                            {formatCurrency(
                              field[
                                "Drone Operation Cost (INR)"
                              ]
                            )}
                          </strong>
                        </div>

                        <div>
                          <span>
                            Setup
                          </span>
                          <strong>
                            {formatCurrency(
                              field[
                                "Setup Cost (INR)"
                              ]
                            )}
                          </strong>
                        </div>

                      </div>

                    </div>

                    {/* TOTAL */}
                    <div className="notification-total">

                      <span>
                        Total Estimated Cost
                      </span>

                      <strong>
                        {formatCurrency(
                          field[
                            "Total Estimated Cost (INR)"
                          ]
                        )}
                      </strong>

                    </div>

                    {/* SMS PREVIEW */}
                    {notification.message && (
                      <details className="sms-preview">

                        <summary>
                          🔔 View SMS Preview
                        </summary>

                        <pre>
                          {notification.message}
                        </pre>

                      </details>
                    )}

                    {/* SEND SMS */}
                    <button
                      type="button"
                      className="notification-send-button"
                      onClick={() =>
                        handleSendSms(
                          notification
                        )
                      }
                      aria-disabled={
                        !notification.eligible ||
                        sendingSurvey ===
                          notification.survey_number ||
                        sendingAll
                      }
                      title={
                        sendingAll
                          ? "Send All is in progress"
                          : notification.eligible
                          ? "Send SMS to this farmer"
                          : "A valid mobile number is required"
                      }
                    >
                      {sendingSurvey ===
                      notification.survey_number
                        ? "Sending..."
                        : notification.sms_status ===
                          "Sent"
                        ? "✓ SMS Sent"
                        : notification.sms_status ===
                          "Preview"
                        ? "✓ Preview Tested"
                        : "🔔 Send SMS"}
                    </button>

                    {!notification.eligible &&
                      notification.error && (
                        <p className="notification-warning">
                          {notification.error}
                        </p>
                      )}

                  </div>
                );
              }
            )}

          </div>

        </div>
      )}

    </div>
  );
};

export default FarmerNotifications;